# -*- coding: utf-8 -*-
"""SD task 2 ( heart)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iTNsBwtZU5ppTxGpqqbrh3UrcRmA2_UM
"""

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
print('Imported')

heart_disease=pd.read_csv("/content/heart.csv")
print("Dataset imported successfully")
heart_disease

heart_disease.shape
heart_disease.isnull().sum()
X=heart_disease.drop(columns='target',axis=1)
Y=heart_disease['target']
print(X)
print(Y)

heart_disease.info()

heart_disease.cp.value_counts()

sns.countplot(x='cp',data=heart_disease)

heart_disease.describe()

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.5,stratify=Y,random_state=2)
print(X.shape,X_train.shape,X_test.shape)
model=LogisticRegression()
model.fit(X_train,Y_train)
print(model.score(X_test,Y_test))

X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)
print('Accuracy on Training data:',training_data_accuracy)
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)
print('Accuracy on Test data:',test_data_accuracy)

input_data=(42,0,2,150,275,0,1,165,0,0.5,2,0,2)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)

if(prediction[0]==0):
    print("The person does not have a heart disease")
else:
    print("The person has heart dsease")